#include "PortF.h"
void PortF_Init(void){
  SYSCTL_RCGCGPIO_R |= GPIOF;
  while((SYSCTL_RCGCGPIO_R & GPIOF)==0){}
  GPIO_PORTF_DIR_R |= LEDS;
  GPIO_PORTF_AFSEL_R &= ~LEDS;
  GPIO_PORTF_DEN_R |= LEDS;
  GPIO_PORTF_AMSEL_R &= ~LEDS;
  GPIO_PORTF_DIR_R &= ~SW1;
  GPIO_PORTF_DEN_R |= SW1;
  GPIO_PORTF_PUR_R |= SW1;
  GPIO_PORTF_IS_R &= ~SW1;
  GPIO_PORTF_IEV_R |= SW1;
  GPIO_PORTF_IM_R |= SW1;
  NVIC_EN0_R |= (1<<30);
}
