#include "portB.h"
void portB_Init(void){
  SYSCTL_RCGCGPIO_R |= PORTB_MASK;
  while((SYSCTL_RCGCGPIO_R & PORTB_MASK)==0){}
  GPIO_PORTB_DIR_R |= TRIGGER_MASK;
  GPIO_PORTB_DIR_R &= ~ECHO_MASK;
  GPIO_PORTB_DEN_R |= B4_B5_MASK;
  GPIO_PORTB_AFSEL_R &= ~B4_B5_MASK;
  GPIO_PORTB_AMSEL_R &= ~B4_B5_MASK;
  GPIO_PORTB_IS_R &= ~ECHO_MASK;
  GPIO_PORTB_IBE_R |= ECHO_MASK;
  GPIO_PORTB_IM_R |= ECHO_MASK;
  NVIC_EN0_R |= 0x02;
}
