#include "PortF.h"
void PortF_Init(void){
  SYSCTL_RCGCGPIO_R |= PORTF;
  while((SYSCTL_RCGCGPIO_R & PORTF)==0){}
  GPIO_PORTF_LOCK_R = 0x4C4F434B;
  GPIO_PORTF_CR_R |= 0x1F;
  GPIO_PORTF_DIR_R |= LEDS;
  GPIO_PORTF_DEN_R |= LEDS;
  GPIO_PORTF_DIR_R &= ~SWITCHES;
  GPIO_PORTF_DEN_R |= SWITCHES;
  GPIO_PORTF_PUR_R |= SWITCHES;
  GPIO_PORTF_IS_R &= ~SWITCHES;
  GPIO_PORTF_IEV_R &= ~SWITCHES;
  GPIO_PORTF_ICR_R = SWITCHES;
  GPIO_PORTF_IM_R |= SWITCHES;
  NVIC_PRI7_R = (NVIC_PRI7_R & 0xFF00FFFF) | LEVEL1;
  NVIC_EN0_R |= 0x40000000;
}
